name: CI
on: [push, pull_request]

jobs:
  build-linux-gcc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -qq valgrind
      - name: build
        run: |
          make -B
      - name: run
        run: |
          make run
      - name: demo
        run: |
          make demo
          cat log_*.txt
        env:
          CC: gcc
          CXX: g++
  build-linux-clang:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -qq git valgrind
      - name: build
        run: |
          make -B
        env:
          CC: clang
          CXX: clang++

